const IS_ACTIVE_CLASSNAME = 'is-active';
const IS_OPEN_CLASSNAME = 'is-open';
const IS_SELECTED_CLASSNAME = 'is-selected';

const COUNTRY_OPTIONS_MENU_TYPE = 'country';
const MEASUREMENT_TITLE = 'Measure';

const TOTAL_TYPE_OPTION = 'Total';
const LAST_DAY_TYPE_OPTION = 'Last day';
const CASES_PARAMETER_OPTION = 'cases';
const DEATHS_PARAMETER_OPTION = 'deaths';
const RECOVERED_PARAMETER_OPTION = 'recovered';
const MEASUREMENT_OPTION = '100k';

const POPULATION_100K = 100000;

const GLOBAL_SECTION_TYPE = 'global';

export {
  IS_ACTIVE_CLASSNAME,
  IS_OPEN_CLASSNAME,
  IS_SELECTED_CLASSNAME,
  COUNTRY_OPTIONS_MENU_TYPE,
  MEASUREMENT_TITLE,
  TOTAL_TYPE_OPTION,
  LAST_DAY_TYPE_OPTION,
  CASES_PARAMETER_OPTION,
  DEATHS_PARAMETER_OPTION,
  RECOVERED_PARAMETER_OPTION,
  MEASUREMENT_OPTION,
  POPULATION_100K,
  GLOBAL_SECTION_TYPE,
};
