const IS_ACTIVE_CLASSNAME = 'is-active';
const IS_OPEN_CLASSNAME = 'is-open';
const IS_SELECTED_CLASSNAME = 'is-selected';

const COUNTRY_OPTIONS_MENU_TYPE = 'country';
const MEASUREMENT_TITLE = 'Measure';

const TOTAL_TYPE_OPTION = 'Total';
const LAST_DAY_TYPE_OPTION = 'Last day';
const CASES_PARAMETER_OPTION = 'cases';
const DEATHS_PARAMETER_OPTION = 'deaths';
const RECOVERED_PARAMETER_OPTION = 'recovered';
const MEASUREMENT_OPTION = '100k';

const POPULATION_100K = 100000;

const GLOBAL_SECTION_TYPE = 'global';

const MAP_BACKGROUND_COLOR_LIGHT = '#aadaff';
const MAP_BACKGROUND_COLOR_DARK = '#393e46';
const OCEAN_COLOR_LIGHT = '#aaeaff';
const OCEAN_COLOR_DARK = '#4c5564';
const FONT_COLOR_LIGHT = '#393E46';
const FONT_COLOR_DARK = '#FFFFFF';
const FILL_MAX_CASES_COLOR = '#FF2105';
const FILL_MAX_DEATH_COLOR = '#393E46';
const FILL_MAX_RECOVERED_COLOR = '#70a800';

const FILL_MIN_ALL_COLOR = '#aac4e7'; // not used yet
const FILL_MIN_CASES_COLOR = '#dcb1a4';
const FILL_MIN_DEATH_COLOR = '#d4d4d4';
const FILL_MIN_RECOVERED_COLOR = '#7ebfb3';

const FILL_ACTIVE_COUNTRY_CASES_COLOR = '#ffff00'; // not used yet
const FILL_ACTIVE_COUNTRY_DEATH_COLOR = '#ffff00'; // not used yet
const FILL_ACTIVE_COUNTRY_RECOVERED_COLOR = '#ffff00'; // not used yet

const STROKE_ACTIVE_COUNTRY_CASES_COLOR = '#ff00ff'; // not used yet
const STROKE_ACTIVE_COUNTRY_DEATH_COLOR = '#ff00ff'; // not used yet
const STROKE_ACTIVE_COUNTRY_RECOVERED_COLOR = '#ff00ff'; // not used yet

const FILL_HOVER_COUNTRY_COLOR = '#67b7dc';
const STROKE_FILL_HOVER_COUNTRY_COLOR = '#37c8ff';

export {
  IS_ACTIVE_CLASSNAME,
  IS_OPEN_CLASSNAME,
  IS_SELECTED_CLASSNAME,
  COUNTRY_OPTIONS_MENU_TYPE,
  MEASUREMENT_TITLE,
  TOTAL_TYPE_OPTION,
  LAST_DAY_TYPE_OPTION,
  CASES_PARAMETER_OPTION,
  DEATHS_PARAMETER_OPTION,
  RECOVERED_PARAMETER_OPTION,
  MEASUREMENT_OPTION,
  POPULATION_100K,
  GLOBAL_SECTION_TYPE,
  MAP_BACKGROUND_COLOR_LIGHT,
  MAP_BACKGROUND_COLOR_DARK,
  OCEAN_COLOR_LIGHT,
  OCEAN_COLOR_DARK,
  FONT_COLOR_LIGHT,
  FONT_COLOR_DARK,
  FILL_MAX_CASES_COLOR,
  FILL_MAX_DEATH_COLOR,
  FILL_MAX_RECOVERED_COLOR,
  FILL_MIN_ALL_COLOR,
  FILL_MIN_CASES_COLOR,
  FILL_MIN_DEATH_COLOR,
  FILL_MIN_RECOVERED_COLOR,
  FILL_ACTIVE_COUNTRY_CASES_COLOR,
  FILL_ACTIVE_COUNTRY_DEATH_COLOR,
  FILL_ACTIVE_COUNTRY_RECOVERED_COLOR,
  STROKE_ACTIVE_COUNTRY_CASES_COLOR,
  STROKE_ACTIVE_COUNTRY_DEATH_COLOR,
  STROKE_ACTIVE_COUNTRY_RECOVERED_COLOR,
  FILL_HOVER_COUNTRY_COLOR,
  STROKE_FILL_HOVER_COUNTRY_COLOR
};
